#!/bin/bash

CONFIG="$HOME/etc/xdg/waybar/config"
STYLE="$HOME/etc/xdg/waybar/style.css"

if [[ ! $(pidof /usr/bin/waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
